default_env:
  :adapter => "sqlite3"
  :database => "./db/mightyape_deals.db"

development:
  :adapter => "sqlite3"
  :database => "./db/mightyape_deals.db"
	
test:
  :adapter => "sqlite3"
  :database => "./db/mightyape_deals.db"
   
production:
  :adapter => "sqlite3"
  :database => "./db/mightyape_deals.db"